[package]
name = "redirect-service"
version = "0.1.0"
edition = "2024"

[dependencies]
storage-service = { path = "../storage-service" }
actix-web = "4.10.2"
mobc = "0.8.5"
mobc-redis = "0.8.2"
tap = "1.0.1"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
